name: 'key_metrics'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=1.10.0"

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'
  enable_key_metrics: true
  enable_key_metrics_regression_test: false

models:
  key_metrics:
    +enabled: "{{ var('enable_key_metrics', true) | as_bool }}"

seeds:
  key_metrics:
    +enabled: "{{ var('enable_key_metrics', true) | as_bool }}"
