{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_disease__neuro_degenerative_disease__amyotrophic_lateral_sclerosis_als') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_disease__neuro_degenerative_disease__amyotrophic_lateral_sclerosis_als') }}
