{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_disease__pulmonary_disease__asthma') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_disease__pulmonary_disease__asthma') }}
