{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_disease__autoimmune_disease__ulcerative_colitis') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_disease__autoimmune_disease__ulcerative_colitis') }}
