{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_disease__cancer__colorectal_cancer') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_disease__cancer__colorectal_cancer') }}
