{{ dq_config_analytical_metric_model('analytical_key_metric__chronic_disease__cardiovascular_disease__stroke_transient_ischemic_attack') }}

{{ dq_analytical_metric_model_sql('data_quality__analytical_key_metric__chronic_disease__cardiovascular_disease__stroke_transient_ischemic_attack') }}
